apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: xnch-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        role: memory
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: xnch-system
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
