apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xnch-data
  namespace: xnch-system
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xnch-vault
  namespace: xnch-system
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 100Gi
